# Generated by Django 3.2.12 on 2022-05-04 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employee.validators
import hris_integration.models.encryption
import employee.models.employee


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hirs_admin", "0032_pre_migration_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("label", models.CharField(default="Primary", max_length=50)),
                ("street1", models.CharField(max_length=128)),
                ("street2", models.CharField(max_length=128, blank=True, null=True)),
                ("street3", models.CharField(max_length=128, blank=True, null=True)),
                ("city", models.CharField(max_length=128)),
                ("province", models.CharField(max_length=128)),
                ("postal_code", models.CharField(max_length=10, blank=True, null=True)),
                ("country", models.CharField(max_length=128)),
                ("primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "address",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("state", models.BooleanField(default=True)),
                ("leave", models.BooleanField(default=False)),
                ("is_inactive", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("middle_name", models.CharField(blank=True, max_length=256)),
                ("suffix", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        unique=True,
                        validators=[employee.validators.UsernameValidator],
                    ),
                ),
                (
                    "email_alias",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        validators=[employee.validators.UPNValidator],
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=64, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_imported", models.BooleanField(default=False)),
                ("is_exported_ad", models.BooleanField(default=False)),
                ("guid", models.CharField(blank=True, max_length=40, null=True)),
                ("nickname", models.CharField(blank=True, max_length=96, null=True)),
                ("designations", models.CharField(blank=True, max_length=256)),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=employee.models.employee.employee_upload_to,
                    ),
                ),
                (
                    "password",
                    hris_integration.models.encryption.PasswordField(
                        blank=True, max_length=128, null=True
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "employee_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("label", models.CharField(default="Primary", max_length=50)),
                ("number", models.CharField(max_length=20)),
                ("primary", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "db_table": "phone_number",
            },
        ),
        migrations.CreateModel(
            name="EmployeeImport",
            fields=[
                ("created_on", models.DateTimeField(auto_now=True, null=True)),
                ("state", models.BooleanField(default=True)),
                ("leave", models.BooleanField(default=False)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("middle_name", models.CharField(blank=True, max_length=256)),
                ("suffix", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        unique=True,
                        validators=[employee.validators.UsernameValidator],
                    ),
                ),
                (
                    "email_alias",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        unique=True,
                        validators=[employee.validators.UPNValidator],
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=64, null=True)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("is_matched", models.BooleanField(default=False)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employee.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_import",
            },
        ),
    ]
