# Generated by Django 3.2.12 on 2022-05-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=512)),
                ('level', models.IntegerField(choices=[(0, 'Critical'), (1, 'Error'), (2, 'Warning'), (3, 'Info')])),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_cleared', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
                ('source_repr', models.CharField(blank=True, max_length=512, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.country')),
            ],
            options={
                'db_table': 'states',
            },
        ),
    ]
