# Generated by Django 3.1.12 on 2021-06-17 13:39

from django.utils import timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('bu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ad_ou', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.businessunit')),
            ],
            options={
                'db_table': 'businessunit',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_on', models.DateField(default=timezone.now)),
                ('updated_on', models.DateTimeField(default=timezone.now)),
                ('givenname', models.CharField(max_length=96)),
                ('middlename', models.CharField(max_length=96)),
                ('surname', models.CharField(max_length=96)),
                ('suffix', models.CharField(max_length=20)),
                ('start_date', models.DateField(default=timezone.now)),
                ('end_date', models.DateField()),
                ('state', models.BooleanField(default=True)),
                ('leave', models.BooleanField(default=True)),
                ('_username', models.CharField(max_length=64)),
                ('photo', models.FileField(upload_to='uploads/')),
                ('_password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('bld_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=256)),
                ('replace', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Job ID')),
                ('name', models.CharField(max_length=255, verbose_name='Job Name')),
                ('seats', models.IntegerField(default=0, verbose_name='Seats')),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.businessunit', verbose_name='Business Units')),
            ],
            options={
                'db_table': 'jobroles',
            },
        ),
        migrations.CreateModel(
            name='GroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=256)),
                ('bu', models.ManyToManyField(to='hirs_admin.BusinessUnit')),
                ('jobs', models.ManyToManyField(to='hirs_admin.JobRole')),
                ('loc', models.ManyToManyField(to='hirs_admin.Location')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('countrycode', models.IntegerField(default=1)),
                ('primary', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.employee')),
            ],
            options={
                'db_table': 'employeepending',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOverrides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=96)),
                ('lastname', models.CharField(max_length=96)),
                ('nickname', models.CharField(max_length=96)),
                ('_username', models.CharField(max_length=128)),
                ('email_alias', models.CharField(max_length=128)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.location')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('street1', models.CharField(max_length=128)),
                ('street2', models.CharField(max_length=128)),
                ('street3', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('primary', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='hirs_admin.JobRole'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_job', to='hirs_admin.jobrole'),
        ),
        migrations.CreateModel(
            name='BusinessUnitManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hirs_admin.businessunit')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee')),
            ],
        ),
    ]
