# Generated by Django 3.1.12 on 2021-07-03 16:35

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0002_auto_20210703_0927'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='setting',
            managers=[
                ('o2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='setting',
            name='_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
