# Generated by Django 3.1.12 on 2021-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0003_auto_20210703_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeoverrides',
            name='_username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employeeoverrides',
            name='email_alias',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employeeoverrides',
            name='firstname',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='employeeoverrides',
            name='lastname',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='employeeoverrides',
            name='nickname',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
    ]
