# Generated by Django 3.1.12 on 2021-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0004_auto_20210705_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeoverrides',
            old_name='email_alias',
            new_name='_email_alias',
        ),
        migrations.RenameField(
            model_name='employeeoverrides',
            old_name='firstname',
            new_name='_firstname',
        ),
        migrations.RenameField(
            model_name='employeeoverrides',
            old_name='lastname',
            new_name='_lastname',
        ),
        migrations.RenameField(
            model_name='employeeoverrides',
            old_name='location',
            new_name='_location',
        ),
    ]
