# Generated by Django 3.1.13 on 2021-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0006_auto_20210710_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeoverrides',
            name='_email_alias',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
