# Generated by Django 3.1.13 on 2021-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0008_remove_employee_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='hirs_admin.JobRole'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=96, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
