# Generated by Django 3.1.13 on 2021-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0009_auto_20210714_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='hirs_admin.JobRole'),
        ),
    ]
