# Generated by Django 3.1.13 on 2021-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0011_auto_20210717_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
