# Generated by Django 3.1.13 on 2021-08-08 15:33

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0014_copy_email_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeoverrides',
            name='_email_alias',
        ),
    ]
