# Generated by Django 3.1.13 on 2021-08-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0017_employeepending_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepending',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_employee', to='hirs_admin.employee'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='guid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
