# Generated by Django 3.1.13 on 2021-09-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0020_csvpending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvpending',
            old_name='lastname',
            new_name='surname',
        ),
    ]
