# Generated by Django 3.1.13 on 2021-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0026_add_employee_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='_field_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='setting',
            field=models.CharField(max_length=768, unique=True),
        ),
    ]
