# Generated by Django 3.1.13 on 2022-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0028_migrate_field_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmapping',
            name='all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='bu_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='jobs_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmapping',
            name='loc_not',
            field=models.BooleanField(default=False),
        ),
    ]
