# Generated by Django 3.1.12 on 2021-07-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0005_auto_20210707_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeoverrides',
            name='_username',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
    ]
