# Generated by Django 3.1.13 on 2021-07-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0007_auto_20210712_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
    ]
