# Generated by Django 3.1.13 on 2021-08-08 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0012_employee_type'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM employeepending"),
        migrations.RemoveField(
            model_name='employeepending',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='_email_alias',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='_email_alias',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='_username',
            field=models.CharField(default='temp123456', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepending',
            name='created_on',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='designation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='firstname',
            field=models.CharField(default='temp123456', max_length=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepending',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='hirs_admin.JobRole'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='lastname',
            field=models.CharField(default='temp123456', max_length=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepending',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.location'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='primary_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_primary_job', to='hirs_admin.jobrole'),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='start_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='status',
            field=models.CharField(choices=[['terminated', 'Terminated'], ['active', 'Active'], ['leave', 'Leave']], default='Active', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepending',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeepending',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='employeeaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeedesignation',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='BusinessUnitManager',
        ),
    ]
