# Generated by Django 3.1.13 on 2021-08-08 15:33

from django.db import migrations

def copy_field(apps, schema_editor):
    EmployeeOverride = apps.get_model('hirs_admin','EmployeeOverrides')
    Employee = apps.get_model('hirs_admin','Employee')
    for emp in EmployeeOverride.objects.all():
        e = Employee.objects.get(emp_id=emp.employee.pk)
        e._email_alias = emp._email_alias
        e.save(update_fields=['_email_alias'])

class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0013_auto_20210808_0933'),
    ]

    operations = [
        migrations.RunPython(copy_field),
    ]
