# Generated by Django 3.1.13 on 2021-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0016_remove_employeepending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepending',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
