# Generated by Django 3.1.13 on 2021-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0019_auto_20210904_0943_squashed_0020_auto_20210904_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvPending',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('givenname', models.CharField(blank=True, max_length=96)),
                ('lastname', models.CharField(blank=True, max_length=96)),
                ('row_data', models.TextField()),
            ],
            options={
                'db_table': 'csv_pending',
            },
        ),
    ]
