# Generated by Django 3.1.13 on 2021-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0023_auto_20210915_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeepending',
            name='_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
