# Generated by Django 3.1.13 on 2021-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0024_auto_20210915_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='guid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
