# Generated by Django 3.1.13 on 2021-12-11 17:05
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0029_auto_20220105_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_on',
            field=models.DateTimeField(null=False, blank=False, default=datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='employeepending',
            name='updated_on',
            field=models.DateTimeField(null=False, blank=False, default=datetime.utcnow),
        ),
    ]
