# Generated by Django 3.2.12 on 2022-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0031_updated_csv_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepending',
            old_name='designation',
            new_name='designations',
        ),
    ]
