# Generated by Django 3.1.14 on 2022-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0031_updated_csv_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=64, unique=True)),
                ('email_subject', models.CharField(max_length=78)),
                ('email_body', models.TextField()),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
    ]
