# Generated by Django 3.2.12 on 2022-04-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hirs_admin', '0033_strip_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='bu_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='csvpending',
            old_name='emp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='jobrole',
            old_name='job_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='bld_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'state': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'state': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
        migrations.AlterField(
            model_name='employeepending',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'state': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hirs_admin.employee'),
        ),
        migrations.AlterModelTable(
            name='employeeaddress',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='employeeoverrides',
            table='employee_overrides',
        ),
        migrations.AlterModelTable(
            name='employeephone',
            table='phone_numbers',
        ),
        migrations.AlterModelTable(
            name='groupmapping',
            table='group_mapping',
        ),
        migrations.AlterModelTable(
            name='wordlist',
            table='word_list',
        ),
    ]
