# Generated by Django 3.2.12 on 2022-05-07 15:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=768, unique=True)),
                ('_value', models.TextField(blank=True, null=True)),
                ('_field_properties', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'setting',
            },
            managers=[
                ('o2', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=256)),
                ('replace', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'word_list',
            },
        ),
    ]
